ARG RUST_VERSION=1.94

FROM rust:${RUST_VERSION}-alpine AS build

WORKDIR /karon

ENV SQLX_OFFLINE=true

RUN apk add nginx bash

RUN --mount=type=cache,target=/usr/local/cargo/registry \
    --mount=type=cache,target=./target \
    --mount=type=bind,source=./Cargo.toml,target=./Cargo.toml \
    --mount=type=bind,source=./Cargo.lock,target=./Cargo.lock \
    --mount=type=bind,source=./src,target=./src \
    --mount=type=bind,source=./templates,target=./templates \
    --mount=type=bind,source=./migrations,target=./migrations \
    \
    cargo build \
    && cp ./target/debug/karon .

EXPOSE 8080

RUN echo "nginx &" >> ./run
RUN echo "./karon" >> ./run

ENTRYPOINT ["bash", "./run" ]
